name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.5
    with:
      init-commands: |
        pnpm exec nx-cloud record -- pnpm docker:test & pnpm docker:services
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx workspace-lint
        pnpm exec nx-cloud record -- pnpm format:check
        pnpm exec nx-cloud record -- pnpm affected:e2e
        pnpm exec nx-cloud record -- pnpm affected:test
      parallel-commands-on-agents: |
        pnpm affected:lint --parallel=3
        pnpm affected:build --parallel=3
        pnpm exec nx affected:test --parallel=3 --ci
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.5
    with:
      number-of-agents: 3
